### ISSUE TITLE
Flexible Menu System with My-Basic for scripting

### ISSUE THREAD

**Issue by enriqueggalvez** [my-basic/awesome#1]
Development environment: Microsoft Visual Studio
Language: C &  C++
Libraries:
   -Allegro 5.2 for graphics
   -My-Basic for scripting

![captura de pantalla 2018-08-10 11 16 04](https://user-images.githubusercontent.com/42243638/43949781-cff11f64-9c8e-11e8-9d4c-279aecb78b87.png)

![captura de pantalla 2018-08-10 11 16 38](https://user-images.githubusercontent.com/42243638/43949841-f89527f8-9c8e-11e8-858b-87929310be82.png)

**Comment by paladin-t** [comment]
Nice! Thanks for sharing. Would you mind making a PR?

**Comment by enriqueggalvez** [comment]
I am a very old and tired man and I do not know ...
What is a PR?

**Comment by paladin-t** [comment]
"Pull request", is often created to modify a forked git repository for further merging into to the source one.

No problem, I added it to the list.
